name: scroll_spy_flutter
description: A Flutter widget that implements scroll spy functionality
version: 0.0.2
homepage: https://github.com/Divyesh84/scroll_spy_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0